export { renderLayout, renderComponent } from "./render"
export { default as HomepageLayout } from "./Homepage"
export { default as ContentLayout } from "./Content"
export { default as CollectionLayout } from "./Collection"
export { default as NotFoundLayout } from "./NotFound"
export { default as SearchSGLayout } from "./SearchSG"
