import * as fs from "fs/promises"
import * as path from "path"

const TYPE_FOLDER = "../src/generated"
const TYPE_FILE = "generatedTypes.ts"
const GENERATED_FILE = "selectableTypes.ts"
const SCHEMA_FILE = "./schema.prisma"

// prisma-kysely drops `Unsupported(...)` columns entirely (it skips fields of
// kind "unsupported" before applying `@kyselyType` doc-comment overrides), so
// we re-inject those fields into the generated Kysely types here, using each
// field's `/// @kyselyType(X)` doc comment in schema.prisma as the emitted
// type. Fields of type `Unsupported(...)` without a `/// @kyselyType(...)`
// doc comment stay omitted, matching prisma-kysely's default behaviour.
const patchUnsupportedColumns = async () => {
  const schema = await fs.readFile(path.join(__dirname, SCHEMA_FILE), "utf8")
  const typesPath = path.join(__dirname, TYPE_FOLDER, TYPE_FILE)
  let types = await fs.readFile(typesPath, "utf8")

  const modelPattern = /model\s+(\w+)\s+\{([\s\S]*?)\n\}/g
  const fieldPattern =
    /\/\/\/\s*@kyselyType\(([^)]+)\)\s*\n\s*(\w+)\s+Unsupported\("[^"]+"\)(\?)?/g

  for (const [, modelName, modelBody] of schema.matchAll(modelPattern)) {
    if (!modelName || !modelBody) {
      continue
    }
    for (const [, kyselyType, fieldName, nullable] of modelBody.matchAll(
      fieldPattern,
    )) {
      if (!kyselyType || !fieldName) {
        continue
      }
      const fieldType = `${kyselyType}${nullable ? " | null" : ""}`
      // prisma-kysely emits `export type X = {...};` (later rewritten to
      // `export interface X {...}` by oxlint's --fix), so handle both forms.
      const headers = [
        {
          header: `export type ${modelName} = {\n`,
          property: `    ${fieldName}: ${fieldType};\n`,
        },
        {
          header: `export interface ${modelName} {\n`,
          property: `  ${fieldName}: ${fieldType}\n`,
        },
      ]
      const match = headers.find(({ header }) => types.includes(header))
      if (!match) {
        throw new Error(
          `Could not find generated type for model ${modelName} while injecting Unsupported column ${fieldName}`,
        )
      }
      // Idempotency guard: `prisma generate` rewrites the file before this
      // script runs, but skip re-injection if the script is run standalone.
      if (new RegExp(`\\b${fieldName}\\s*[?:]`).test(types)) {
        continue
      }
      types = types.replace(match.header, match.header + match.property)
    }
  }

  await fs.writeFile(typesPath, types)
}

const extractTableTypes = (source: string): string[] => {
  // prisma-kysely emits either `export type DB = { ... };` or `export interface DB { ... }`.
  const dbBody =
    source.match(/export type DB\s*=\s*\{([\s\S]*?)\};?/)?.[1] ??
    source.match(/export interface DB\s*\{([\s\S]*?)\};?/)?.[1]

  if (!dbBody) {
    throw new Error("Could not find DB type definition in generatedTypes.ts")
  }

  const tables: string[] = []
  for (const line of dbBody.split("\n")) {
    // Match `TableName: TableType` lines; Prisma model names are valid TS identifiers.
    const tableName = line.match(/^\s*([A-Za-z_]\w*)\s*:/)?.[1]
    if (tableName) {
      tables.push(tableName)
    }
  }

  if (tables.length === 0) {
    throw new Error("No tables found in DB type definition")
  }

  return tables
}

const buildSelectableTypes = (tableTypes: string[]): string => {
  const exports = tableTypes
    .map((table) => `export type ${table} = Selectable<T.${table}>`)
    .join("\n")

  return [
    "// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT IT MANUALLY.",
    'import { type Selectable } from "kysely"',
    "",
    'import type * as T from "./generatedTypes"',
    exports,
    "",
  ].join("\n")
}

export const generate = async () => {
  await patchUnsupportedColumns()

  const inputPath = path.join(__dirname, TYPE_FOLDER, TYPE_FILE)
  const source = await fs.readFile(inputPath, "utf-8")
  const tableTypes = extractTableTypes(source)
  const outputPath = path.join(__dirname, TYPE_FOLDER, GENERATED_FILE)
  await fs.writeFile(outputPath, buildSelectableTypes(tableTypes))
}

generate().catch((error) => {
  console.error(error)
  process.exit(1)
})
