import fs from "node:fs/promises"
import path from "node:path"
import ts from "typescript"

// oxlint-disable unicorn/prefer-module -- CommonJS .cts script; __dirname is provided by tsx

const TYPE_FOLDER = "../src/generated"
// THIS MUST BE PREFIXED WITH A DOT
const TYPE_FILE = "./generatedTypes.ts"
const GENERATED_FILE = "./selectableTypes.ts"
const SCHEMA_FILE = "./schema.prisma"

// prisma-kysely drops `Unsupported(...)` columns entirely (it skips fields of
// kind "unsupported" before applying `@kyselyType` doc-comment overrides), so
// we re-inject those fields into the generated Kysely types here, using each
// field's `/// @kyselyType(X)` doc comment in schema.prisma as the emitted
// type. Fields of type `Unsupported(...)` without a `/// @kyselyType(...)`
// doc comment stay omitted, matching prisma-kysely's default behaviour.
const patchUnsupportedColumns = async () => {
  const schema = await fs.readFile(path.join(__dirname, SCHEMA_FILE), "utf-8")
  const typesPath = path.join(__dirname, TYPE_FOLDER, TYPE_FILE)
  let types = await fs.readFile(typesPath, "utf-8")

  const modelPattern =
    /model\s+(?<modelName>\w+)\s+\{(?<modelBody>[\s\S]*?)\n\}/gu
  const fieldPattern =
    /\/\/\/\s*@kyselyType\((?<kyselyType>[^)]+)\)\s*\n\s*(?<fieldName>\w+)\s+Unsupported\("[^"]+"\)(?<nullable>\?)?/gu

  for (const match of schema.matchAll(modelPattern)) {
    const { modelName, modelBody } = match.groups ?? {}
    if (modelName === undefined || modelBody === undefined) {
      continue
    }
    for (const fieldMatch of modelBody.matchAll(fieldPattern)) {
      const { kyselyType, fieldName, nullable } = fieldMatch.groups ?? {}
      if (kyselyType === undefined || fieldName === undefined) {
        continue
      }
      const fieldType = `${kyselyType}${nullable === "?" ? " | null" : ""}`
      // prisma-kysely emits `export type X = {...};` (later rewritten to
      // `export interface X {...}` by oxlint's --fix), so handle both forms.
      const headers = [
        {
          header: `export type ${modelName} = {\n`,
          property: `    ${fieldName}: ${fieldType};\n`,
        },
        {
          header: `export interface ${modelName} {\n`,
          property: `  ${fieldName}: ${fieldType}\n`,
        },
      ]
      let matchedHeader: (typeof headers)[number] | undefined
      for (const header of headers) {
        if (types.includes(header.header)) {
          matchedHeader = header
          break
        }
      }
      if (matchedHeader === undefined) {
        throw new Error(
          `Could not find generated type for model ${modelName} while injecting Unsupported column ${fieldName}`,
        )
      }
      // Idempotency guard: `prisma generate` rewrites the file before this
      // script runs, but skip re-injection if the script is run standalone.
      if (new RegExp(`\\b${fieldName}\\s*[?:]`, "u").test(types)) {
        continue
      }
      types = types.replace(
        matchedHeader.header,
        matchedHeader.header + matchedHeader.property,
      )
    }
  }

  await fs.writeFile(typesPath, types)
}

const KYSELY_IMPORT = ts.factory.createImportDeclaration(
  undefined,
  ts.factory.createImportClause(
    undefined,
    undefined,
    ts.factory.createNamedImports([
      ts.factory.createImportSpecifier(
        true,
        undefined,
        ts.factory.createIdentifier("Selectable"),
      ),
    ]),
  ),
  ts.factory.createStringLiteral("kysely"),
)

const GENERATED_IMPORT = ts.factory.createImportDeclaration(
  undefined,
  ts.factory.createImportClause(
    ts.SyntaxKind.TypeKeyword,
    undefined,
    ts.factory.createNamespaceImport(ts.factory.createIdentifier("T")),
  ),
  ts.factory.createStringLiteral(TYPE_FILE.replace(/\.ts$/u, "")),
)

const HEADER = [
  ts.addSyntheticLeadingComment(
    KYSELY_IMPORT,
    ts.SyntaxKind.SingleLineCommentTrivia,
    " THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT IT MANUALLY.",
    true,
  ),
  GENERATED_IMPORT,
]

const extractTableTypes = (source: ts.SourceFile) => {
  let database: ts.TypeAliasDeclaration | undefined

  for (const statement of source.statements) {
    if (!ts.isTypeAliasDeclaration(statement)) {
      continue
    }
    if (statement.name.text !== "DB") {
      continue
    }
    database = statement
    break
  }

  if (database === undefined) {
    throw new Error("Could not find DB type alias in generated types file")
  }

  if (!ts.isTypeLiteralNode(database.type)) {
    throw new Error("DB type alias must be a type literal")
  }

  const tables: string[] = []

  for (const entry of database.type.members) {
    if (!ts.isPropertySignature(entry)) {
      continue
    }
    const { type: propertyType } = entry
    if (propertyType === undefined || !ts.isTypeReferenceNode(propertyType)) {
      continue
    }
    const { typeName } = propertyType
    if (!ts.isIdentifier(typeName)) {
      continue
    }
    tables.push(typeName.getText(source))
  }
  return tables
}

export const generate = async () => {
  await patchUnsupportedColumns()

  const file = await fs.readFile(path.join(__dirname, TYPE_FOLDER, TYPE_FILE))
  const source = ts.createSourceFile(
    TYPE_FILE,
    file.toString(),
    ts.ScriptTarget.ES2015,
  )

  const tableTypes = extractTableTypes(source)

  const printer = ts.createPrinter({ newLine: ts.NewLineKind.LineFeed })

  const statements: ts.Statement[] = [...HEADER]

  for (const tableType of tableTypes) {
    statements.push(
      ts.factory.createTypeAliasDeclaration(
        [ts.factory.createModifier(ts.SyntaxKind.ExportKeyword)],
        ts.factory.createIdentifier(tableType),
        undefined,
        ts.factory.createTypeReferenceNode(
          ts.factory.createIdentifier("Selectable"),
          [
            ts.factory.createTypeReferenceNode(
              ts.factory.createQualifiedName(
                ts.factory.createIdentifier("T"),
                ts.factory.createIdentifier(tableType),
              ),
            ),
          ],
        ),
      ),
    )
  }

  const target = ts.factory.createSourceFile(
    statements,
    ts.factory.createToken(ts.SyntaxKind.EndOfFileToken),
    ts.NodeFlags.None,
  )

  const output_file = path.join(__dirname, TYPE_FOLDER, GENERATED_FILE)

  await fs.writeFile(output_file, printer.printFile(target))
}

void (async () => {
  try {
    await generate()
  } catch (error: unknown) {
    console.log(error)
  }
})()