export const ARRAY_RADIO_FORMAT = "radio"
export const HERO_ACTION_LAYOUT_FORMAT = "hero-action-layout"
export const HERO_QUICK_ACTIONS_FORMAT = "hero-quick-actions"
export const COLLECTION_DROPDOWN_FORMAT = "collection-dropdown"
export const DGS_DATASET_ID_FORMAT = "dgs-dataset-id"
export const ICON_PICKER_FORMAT = "icon-picker"
export const TAG_CATEGORY_ITEM_FORMAT = "tag-category-item"
