export const ARRAY_RADIO_FORMAT = "radio"
export const HERO_BLOCK_IMAGE_FORMAT = "heroBlockImage"
export const COLLECTION_DROPDOWN_FORMAT = "collection-dropdown"
export const DGS_DATASET_ID_FORMAT = "dgs-dataset-id"
export const TAG_CATEGORY_ITEM_FORMAT = "tag-category-item"
