name: "Setup and install"
description: "Common setup steps for Actions"

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5
      with:
        version: 11.1.1

    - uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: pnpm
        cache-dependency-path: pnpm-lock.yaml

    - shell: bash
      run: pnpm install --frozen-lockfile
