name: "Setup and install"
description: "Common setup steps for Actions"

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 22

    - uses: oven-sh/setup-bun@635640504f6d7197d3bb29876a652f671028dc97
      with:
        bun-version: "1.3.5"

    - shell: bash
      run: bun add -g turbo

    - shell: bash
      run: bun install --frozen-lockfile
