export { default as ArticleLayout } from "./Article"
export { default as CollectionLayout } from "./Collection"
export { default as ContentLayout } from "./Content"
export { default as HomepageLayout } from "./Homepage"
export { default as NotFoundLayout } from "./NotFound"
export { default as SearchLayout } from "./Search"
