version: "3"

services:
  studio:
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: ./apps/studio/Dockerfile
    depends_on:
      - postgres
    # NOTE: try to restart container if it's stopped.
    # if manual stop, restarts on next enter
    restart: always
    env_file:
      - .env
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - postgres-volume:/var/lib/postgresql/data

volumes:
  postgres-volume:
