import {
  IS_SINGPASS_ENABLED_FEATURE_KEY,
  IS_SINGPASS_ENABLED_FEATURE_KEY_FALLBACK_VALUE,
  COLLECTION_WIDGET_ENABLED_FEATURE_KEY,
  COLLECTION_WIDGET_ENABLED_FEATURE_KEY_FALLBACK_VALUE,
} from "~/lib/growthbook"

const mockFeatureFlags = new Map<string, unknown>([
  [
    IS_SINGPASS_ENABLED_FEATURE_KEY,
    IS_SINGPASS_ENABLED_FEATURE_KEY_FALLBACK_VALUE,
  ],
  [
    COLLECTION_WIDGET_ENABLED_FEATURE_KEY,
    COLLECTION_WIDGET_ENABLED_FEATURE_KEY_FALLBACK_VALUE,
  ],
])

export { mockFeatureFlags }
