import type { Transaction as NativeTransaction } from "kysely";
import { Kysely as NativeKysely } from "kysely";

/**
 * Do not edit ./generatedTypes and ./generatedEnums files directly.
 * They are auto generated by kysely-prisma.
 */
export * from "./augmentedTypes";
export * as Model from "./generatedTypes";
export type { DB } from "./generatedTypes";
export * from "./generatedEnums";
export * from "./selectableTypes";
export type { Insertable, Updateable, QueryNode } from "kysely";
export { sql } from "kysely";

export class Kysely<DB> extends NativeKysely<DB> {
  static readonly #identifier: unique symbol = Symbol();

  #identity(): symbol {
    return (Kysely<DB>).#identifier;
  }
}

export type Transaction<DB> = Omit<NativeTransaction<DB>, "transaction">;

export type SafeKysely<DB> = Transaction<DB> | Kysely<DB>;
