export * from "./IconFlickr"
export * from "./IconInstagram"
export * from "./IconOneColumnLayout"
export * from "./IconTwoColumnLayout"
export * from "./IconWhatsApp"
export * from "./IconBoxes"
export * from "./IconRows"
