import type { GazetteTableData } from "./components"

export const MOCK_GAZETTES: GazetteTableData[] = [
  {
    id: "1",
    notificationNo: "2133",
    title: "Sample Gazette title to show statuses",
    category: "Government Gazette",
    subcategory: "Notices under other Acts",
    status: "publish-failure",
    fileId: "26gg2228.pdf",
    fileUrl: null,
    publishTime: new Date("2026-04-18T17:55:00"),
  },
  {
    id: "2",
    notificationNo: null,
    title: "Sample Gazette title to show statuses",
    category: "Government Gazette",
    subcategory: "Advertisements",
    status: "scanning-failure",
    fileId: "26adv5737.pdf",
    fileUrl: null,
    publishTime: new Date("2026-04-17T17:55:00"),
  },
  {
    id: "3",
    notificationNo: null,
    title: "Sample Gazette title to show statuses",
    category: "Government Gazette",
    subcategory: "Advertisements",
    status: "parsing-failure",
    fileId: "26adv2227.pdf",
    fileUrl: null,
    publishTime: new Date("2026-04-16T17:55:00"),
  },
  {
    id: "4",
    notificationNo: "2111",
    title: "Sample Gazette title to show statuses",
    category: "Government Gazette",
    subcategory: "Notices under other Acts",
    status: "upload-failure",
    fileId: "26gg2226.pdf",
    fileUrl: null,
    publishTime: new Date("2026-04-16T17:55:00"),
  },
  {
    id: "5",
    notificationNo: "2149",
    title:
      "Workplace Safety and Health Act 2006 - Sri Yahweh Van Ram shall cease to be Inspector",
    category: "Government Gazette",
    subcategory: "Notices under other Acts",
    status: "scanning",
    fileId: "26gg2225.pdf",
    fileUrl: null,
    publishTime: new Date("2026-04-18T17:55:00"),
  },
  {
    id: "6",
    notificationNo: "2148",
    title: "Variable Capital Companies Act (2018) - Section 33",
    category: "Government Gazette",
    subcategory: "Notices under other Acts",
    status: "scanning",
    fileId: "26gg5737.pdf",
    fileUrl: null,
    publishTime: new Date("2026-04-18T17:55:00"),
  },
  {
    id: "7",
    notificationNo: "2147",
    title: "Variable Capital Companies Act (2018) - Section 33",
    category: "Government Gazette",
    subcategory: "Notices under other Acts",
    status: "scheduled",
    fileId: "26gg5736.pdf",
    fileUrl: "https://example.com/26gg5736.pdf",
    publishTime: new Date("2026-04-17T17:55:00"),
  },
  {
    id: "8",
    notificationNo: "2146",
    title: "Limited Liability Partnerships Act 2005 - Section 64",
    category: "Government Gazette",
    subcategory: "Notices under other Acts",
    status: "scheduled",
    fileId: "26gg5735.pdf",
    fileUrl: "https://example.com/26gg5735.pdf",
    publishTime: new Date("2026-04-17T17:55:00"),
  },
  {
    id: "9",
    notificationNo: "2145",
    title: "Limited Liability Partnerships Act 2005 - Section 64",
    category: "Government Gazette",
    subcategory: "Notices under other Acts",
    status: "published",
    fileId: "26gg5734.pdf",
    fileUrl: "https://example.com/26gg5734.pdf",
    publishTime: new Date("2026-04-17T17:55:00"),
  },
  {
    id: "10",
    notificationNo: "2144",
    title:
      "Foreign Employee Dormitories Act 2015 - Low Yue Ling Charlynn appointed to be Deputy Commissioner",
    category: "Government Gazette",
    subcategory: "Notices under other Acts",
    status: "published",
    fileId: "26gg5733.pdf",
    fileUrl: "https://example.com/26gg5733.pdf",
    publishTime: new Date("2026-04-17T17:55:00"),
  },
  {
    id: "11",
    notificationNo: "2143",
    title:
      "Foreign Employee Dormitories Act 2015 - Low Yue Ling Charlynn shall cease to be Assistant Commissioner",
    category: "Government Gazette",
    subcategory: "Notices under other Acts",
    status: "published",
    fileId: "26gg5732.pdf",
    fileUrl: "https://example.com/26gg5732.pdf",
    publishTime: new Date("2026-04-17T17:55:00"),
  },
  {
    id: "12",
    notificationNo: "2142",
    title:
      "Employment of Foreign Manpower Act 1990 - Chua Geng Leong shall cease to be Employment Inspector",
    category: "Government Gazette",
    subcategory: "Notices under other Acts",
    status: "published",
    fileId: "26gg5731.pdf",
    fileUrl: "https://example.com/26gg5731.pdf",
    publishTime: new Date("2026-04-17T17:55:00"),
  },
  {
    id: "13",
    notificationNo: "2141",
    title: "Employment Claims Act 2016 - Appointment of approved mediator",
    category: "Government Gazette",
    subcategory: "Notices under other Acts",
    status: "published",
    fileId: "26gg5730.pdf",
    fileUrl: "https://example.com/26gg5730.pdf",
    publishTime: new Date("2026-04-17T17:55:00"),
  },
  {
    id: "14",
    notificationNo: "2140",
    title:
      "Employment Agencies Act 1958 - Low Yue Ling Charlynn appointed to be Deputy Commissioner",
    category: "Government Gazette",
    subcategory: "Notices under other Acts",
    status: "published",
    fileId: "26gg5729.pdf",
    fileUrl: "https://example.com/26gg5729.pdf",
    publishTime: new Date("2026-04-17T17:55:00"),
  },
  {
    id: "15",
    notificationNo: "2139",
    title:
      "Employment Agencies Act 1958 - Low Yue Ling Charlynn shall cease to be Assistant Commissioner",
    category: "Government Gazette",
    subcategory: "Notices under other Acts",
    status: "published",
    fileId: "26gg5728.pdf",
    fileUrl: "https://example.com/26gg5728.pdf",
    publishTime: new Date("2026-04-17T17:55:00"),
  },
]
