export const COMPONENT_IMPORTS: Record<string, string> = {
  accordion: "Accordion",
  audio: "Audio",
  blockquote: "Blockquote",
  callout: "Callout",
  childrenpages: "ChildrenPages",
  collectionblock: "CollectionBlock",
  contactinformation: "ContactInformation",
  contentpic: "Contentpic",
  dynamiccomponentlist: "DynamicComponentList",
  dynamicdatabanner: "DynamicDataBanner",
  formsg: "FormSG",
  hero: "Hero",
  iframe: "Iframe",
  image: "Image",
  imagegallery: "ImageGallery",
  infobar: "Infobar",
  infocards: "InfoCards",
  infocols: "InfoCols",
  infopic: "Infopic",
  keystatistics: "KeyStatistics",
  logocloud: "LogoCloud",
  map: "Map",
  prose: "Prose",
  video: "Video",
}

export const LAYOUT_IMPORTS: Record<string, string> = {
  article: "ArticleLayoutSkeleton",
  collection: "CollectionLayout",
  content: "ContentLayoutSkeleton",
  database: "DatabaseLayoutSkeleton",
  homepage: "HomepageLayoutSkeleton",
  index: "IndexPageLayoutSkeleton",
  notfound: "NotFoundLayout",
  search: "SearchLayout",
}
