version: "3"

services:
  postgres:
    image: postgres:15.10@sha256:d609c3005478af92bddad773423df829b7402ea0b356d5b72edd2fd54d1ad3ea
    ports:
      - 5431:5432
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - postgres-volume:/var/lib/postgresql-pgboss-test/data

volumes:
  postgres-volume:
