export { default as antiSlop } from "ultracite/oxlint/anti-slop"
export { default as core } from "ultracite/oxlint/core"
export { default as next } from "ultracite/oxlint/next"
export { default as react } from "ultracite/oxlint/react"
export { default as vitest } from "ultracite/oxlint/vitest"
