# Workflow name
name: "Chromatic"

# Event for the workflow
on:
  pull_request:
    types: [opened, reopened, synchronize]

  push:
    branches:
      - main

# List of jobs
jobs:
  optimize_ci:
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.check_skip.outputs.skip }}
    steps:
      - name: Optimize CI
        id: check_skip
        uses: withgraphite/graphite-ci-action@402a89bc8aa6db18ae1f9c61953d001d5f9d828f
        with:
          graphite_token: ${{ secrets.GRAPHITE_CI_OPTIMIZER_TOKEN }}
  # JOB to run change detection
  changes:
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      ui: ${{ steps.filter.outputs.ui }}
      studio: ${{ steps.filter.outputs.studio }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      # For pull requests it's not necessary to checkout the code
      - uses: dorny/paths-filter@7b450fff21473bca461d4b92ce414b9d0420d706
        id: filter
        with:
          filters: |
            ui:
              - 'packages/components/**'
            studio:
              - 'apps/studio/**'
              - 'packages/components/src/interfaces/**'
              - 'packages/components/src/types/**'
  ui:
    needs: [changes, optimize_ci]
    # Only run if the user is not a bot and has changes
    if: ${{ !endsWith(github.actor , 'bot') && !endsWith(github.actor, '[bot]') && needs.changes.outputs.ui == 'true' && needs.optimize_ci.outputs.skip == 'false'}}
    # Operating System
    runs-on: ubuntu-latest
    environment: staging
    # Job steps
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0 # Required for v4
      - name: Setup
        uses: ./.github/actions/setup
      # 👇 Adds Chromatic as a step in the workflow
      - name: Publish to Chromatic
        uses: chromaui/action@94713c544284a14195de3b50ef24301579f1877e # v18.0.1
        # Chromatic GitHub Action options
        with:
          workingDir: packages/components
          storybookBaseDir: packages/components
          projectToken: ${{ secrets.CHROMATIC_COMPONENTS_PROJECT_TOKEN }}
          onlyChanged: true
          exitOnceUploaded: true
          autoAcceptChanges: main
  studio:
    needs: [changes, optimize_ci]
    # Only run if the user is not a bot and has changes
    if: ${{ !endsWith(github.actor , 'bot') && !endsWith(github.actor, '[bot]') && needs.changes.outputs.studio == 'true' && needs.optimize_ci.outputs.skip == 'false' }}
    # Operating System
    runs-on: ubuntu-latest
    environment: staging
    # Job steps
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0 # Required for v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Build Isomer Components
        run: pnpm --filter @opengovsg/isomer-components run build
      # Storybook bundles @prisma/client; Prisma's browser shim requires a generated client (not created by pnpm install).
      - name: Generate Prisma client
        run: pnpm --filter @isomer/db generate
      - name: Build preview-tw CSS
        run: pnpm --filter isomer-studio run build:preview-tw
      # 👇 Adds Chromatic as a step in the workflow
      - name: Publish to Chromatic
        uses: chromaui/action@94713c544284a14195de3b50ef24301579f1877e # v18.0.1
        # Chromatic GitHub Action options
        with:
          workingDir: apps/studio
          storybookBaseDir: apps/studio
          projectToken: ${{ secrets.CHROMATIC_STUDIO_PROJECT_TOKEN }}
          onlyChanged: true
          exitOnceUploaded: true
          autoAcceptChanges: main
