name: Deploy to uat

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - uat

jobs:
  deploy_uat:
    name: Deploy app to uat
    uses: ./.github/workflows/aws_deploy.yml
    with:
      aws-region: "ap-southeast-1"
      aws-account-id: "343218177745"
      cicd-role: "arn:aws:iam::343218177745:role/isomer-next-infra-github-oidc-role-d2e1bd3"
      ecr-repository: "isomer-next-infra-uat-ecr"
      ecs-cluster-name: "studio-uat-ecs"
      ecs-service-name: "studio-uat-ecs-service"
      ecs-container-name: "studio"
      ecs-container-port: 3000
      environment: "uat"
      shortEnv: "uat"
      codedeploy-appspec-path: .aws/deploy/appspec.json
      ecs-task-definition-path: .aws/deploy/task-definition.json
      codedeploy-application: "studio-uat-ecs-app"
      codedeploy-deployment-group: "studio-uat-ecs-dg"
      ecs-task-role: studio-uat-ecs-task-role
      ecs-task-exec-role: studio-uat-ecs-task-exec-role
      app-url: "https://uat-studio.isomer.gov.sg"
      app-name: "Isomer Studio (UAT)"
      app-version: ${{ github.sha }}
      app-enable-sgid: false
      app-s3-region: "ap-southeast-1"
      app-s3-assets-bucket-name: "isomer-next-infra-uat-assets-private-e728930"
      app-s3-assets-domain-name: "isomer-user-content-uat.by.gov.sg"
      app-growthbook-client-key: "sdk-x4jkIJGr4TizR8qK"
      app-intercom-app-id: "jv2tjc3g"

    secrets:
      DD_API_KEY: ${{ secrets.DD_API_KEY_GITHUB_ACTIONS }}
