name: Deploy to vapt

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - vapt

# NOTE: This is actually using our federated isomer-staging account
jobs:
  deploy_staging:
    name: Deploy app to vapt
    uses: ./.github/workflows/aws_deploy.yml
    # NOTE: deploy in `staging` env to set env specific secrets
    with:
      aws-region: "ap-southeast-1"
      aws-account-id: "058264420411"
      cicd-role: "arn:aws:iam::058264420411:role/isomer-next-infra-github-oidc-role-b58f3de"
      ecr-repository: "isomer-next-infra-vapt-ecr"
      ecs-cluster-name: "studio-vapt-ecs"
      ecs-service-name: "studio-vapt-ecs-service"
      ecs-container-name: "studio"
      ecs-container-port: 3000
      environment: "vapt"
      shortEnv: "vapt"
      codedeploy-appspec-path: .aws/deploy/appspec.json
      ecs-task-definition-path: .aws/deploy/task-definition.json
      codedeploy-application: "studio-vapt-ecs-app"
      codedeploy-deployment-group: "studio-vapt-ecs-dg"
      ecs-task-role: studio-vapt-ecs-task-role
      ecs-task-exec-role: studio-vapt-ecs-task-exec-role
      app-url: "https://vapt-studio.isomer.gov.sg"
      app-name: "Isomer Studio (VAPT)"
      app-version: ${{ github.sha }}
      app-enable-sgid: true
      app-s3-region: "ap-southeast-1"
      app-s3-assets-bucket-name: "isomer-next-infra-vapt-assets-private-ab628e1"
      app-s3-assets-domain-name: "isomer-user-content-vapt.by.gov.sg"

    secrets:
      DD_API_KEY: ${{ secrets.DD_API_KEY_GITHUB_ACTIONS }}
      RDS_READER_ENDPOINT: ${{ secrets.RDS_READER_ENDPOINT }}
