name: Deploy to vapt

concurrency:
  group: deploy-vapt-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - vapt

jobs:
  deploy_vapt:
    name: Deploy app to vapt
    uses: ./.github/workflows/aws_deploy.yml
    with:
      aws-region: "ap-southeast-1"
      aws-account-id: "" # TODO
      cicd-role: "" # TODO
      ecr-repository: "isomer-next-infra-vapt-ecr"
      ecs-cluster-name: "studio-vapt-ecs"
      ecs-service-name: "studio-vapt-ecs-service"
      ecs-container-name: "studio"
      ecs-container-port: 3000
      environment: "vapt"
      shortEnv: "vapt"
      codedeploy-appspec-path: .aws/deploy/appspec.json
      ecs-task-definition-path: .aws/deploy/task-definition.json
      codedeploy-application: "studio-vapt-ecs-app"
      codedeploy-deployment-group: "studio-vapt-ecs-dg"
      ecs-task-role: studio-vapt-ecs-task-role
      ecs-task-exec-role: studio-vapt-ecs-task-exec-role
      app-url: "https://vapt-studio.isomer.gov.sg"
      app-name: "Isomer Studio (VAPT)"
      app-version: ${{ github.sha }}
      app-s3-region: "ap-southeast-1"
      app-s3-assets-bucket-name: "isomer-next-infra-vapt-assets-private-e728930"
      app-s3-assets-domain-name: "isomer-user-content-vapt.by.gov.sg"
      app-growthbook-client-key: "" # TODO
      app-intercom-app-id: "jv2tjc3g"

    secrets:
      DD_API_KEY: ${{ secrets.DD_API_KEY_GITHUB_ACTIONS }}
