name: Delete Neon Branch

on:
  pull_request:
    types: [closed]

jobs:
  delete-neon-branch:
    # Additional guard to ensure main is never deleted
    if: github.head_ref != 'main'
    runs-on: ubuntu-latest
    steps:
      - uses: neondatabase/delete-branch-action@ed7d9bfda9b787d3269d18596eea76633ec34fe2
        with:
          project_id: ${{ secrets.NEON_PROJECT_ID }}
          branch: preview/${{ github.head_ref }}
          # Note: This points to neon project-scoped api key: isomer-studio-postgres
          api_key: ${{ secrets.NEON_API_KEY }}
